--------------------------------------------------------
--  文件已创建 - 星期五-四月-05-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GOODSINFO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GOODSINFO" 
   (	"GOODSID" NUMBER(*,0), 
	"GOODSNAME" VARCHAR2(50 BYTE), 
	"GOODSPRICE" NUMBER(7,2), 
	"GOODSTYPE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TABLE1_PK" ON "SYSTEM"."GOODSINFO" ("GOODSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GOODSINFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GOODSINFO" MODIFY ("GOODSID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GOODSINFO" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("GOODSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
